alias v="nvim"
alias vz="nvim $ZDOTDIR/.zshrc"
alias so="source $ZDOTDIR/.zshrc"
alias c="clear"
alias cc="clear && code ."
alias ls="eza --icons --group-directories-first --oneline --no-quotes"
alias ll="eza --all --icons --group-directories-first --oneline --no-quotes"
alias tree="eza --tree --no-quotes"
alias fzf='fzf --preview "bat --style=plain --color=always {}"'
alias pf="fzf --preview 'bat --style=plain --color=always {}' --bind shift-up:preview-page-up,shift-down:preview-page-down"
alias bat="bat --style=numbers --color=always"
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias buu="brew update; brew upgrade"
alias pbcopy="xclip -selection clipboard"
alias pbpaste="xclip -selection clipboard -o"
alias cf="pbcopy < $1"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"
alias sudo="sudo "
