alias v="nvim"
alias vz="chezmoi edit --apply $ZDOTDIR/.zshrc"
alias so="exec zsh"
alias c="clear"
alias cc="clear && code ."
alias ls="eza --icons --group-directories-first --oneline --no-quotes"
alias ll="eza --all --icons --group-directories-first --oneline --no-quotes"
alias tree="eza --tree --no-quotes"
alias fzf='fzf --preview "bat --style=plain --color=always {}"'
alias pf="fzf --preview 'bat --style=plain --color=always {}' --bind shift-up:preview-page-up,shift-down:preview-page-down"
alias bat="bat --style=numbers --color=always"
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias pbcopy="clip.exe"
alias pbpaste="powershell.exe -command 'Get-Clipboard'"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd..="cd .."
alias sudo="sudo "
